#API
serenity.project.name=AE Network
APIserenity.compress.filenames=false
serenity.logging=VERBOSE
serenity.reports.show.step.details=true
serenity.outputDirectory=target/site/reports
serenity.sourcesDirectory=target/site/reports
serenity.console.colors=true
serenity.report.accessibility=true
serenity.report.show.rest.query=true
serenity.report.show.rest.response=true
serenity.report.show.rest.requests=true
serenity.report.show.rest.calls=true
serenity.rest.report.calls=true
serenity.rest.log.all=true
#report.customfields.ApplicationVersion = 1.2.3
#report.customfields.environment = ${environment}
#report.customfields.order=ApplicationVersion,environment
#environment=DEV
#serenity.environment=DEV
spring.profiles.active=dev
#UI
driver=headless-chrome-proxy
region = Apigee
#  Apigee
indicator = V
cardType = PREPAID
#headless-chrome
#driver = firefox
context=chrome
screenDimension=FULL_SCREEN
chrome.switches=--headless,--window-size=1920,1080;
# Supported Drivers: Chrome, Firefox
# Supported Environments: DEV, QA
# Supported Resolutions: FULL_SCREEN, TABLET_PORTRAIT, MOBILE_PORTRAIT,
# Customise your requirements hierarchy
serenity.test.root=com.ae.network.ui
serenity.requirement.types=theme,feature,epic
serenity.restart.browser.for.each=NEVER
#serenity.use.unique.browser=true
serenity.dry.run=false
serenity.verbose.steps=true
screenshot.dir=target/
# How long does Serenity waits for elements that are not present on the screen to load
webdriver.timeouts.implicitlywait=10000
current.target.version = sprint-1
serenity.take.screenshots.for.tasks=after_each_step
serenity.take.screenshots.for.interactions=for_failure
serenity.take.screenshots.for.questions=after_each_step
#screenshot.dir=test-output/
screenshot.rel.path=../